#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2024 MoonlightByte
# SPDX-License-Identifier: Fair-Source-1.0
# License: See LICENSE file in the repository root
# This software is subject to the terms of the Fair Source License.

"""
Location Generator Script
Creates detailed location JSON files based on schema requirements and plot needs.
"""

import copy
import json
import os
import re
from dataclasses import dataclass
from typing import Any, Dict, List

from core.ai import api_client
import config
import jsonschema
from utils.module_path_manager import ModulePathManager
from utils.encoding_utils import normalize_typography_deep
from utils.capture.multi_model_capture import (
    capture_and_fanout,
    register_callsite,
)
from model_config import convert_to_gemini_schema

register_callsite("T025", "core/generators/location_generator.py", 693)
register_callsite("T026", "core/generators/location_generator.py", 884)


_T026_OFFICIAL_SKILLS = frozenset(
    {
        "Acrobatics",
        "Animal Handling",
        "Arcana",
        "Athletics",
        "Deception",
        "History",
        "Insight",
        "Intimidation",
        "Investigation",
        "Medicine",
        "Nature",
        "Perception",
        "Performance",
        "Persuasion",
        "Religion",
        "Sleight of Hand",
        "Stealth",
        "Survival",
    }
)
_T026_CALENDAR_MONTHS = (
    "Firstmonth",
    "Coldmonth",
    "Thawmonth",
    "Springmonth",
    "Bloommonth",
    "Sunmonth",
    "Heatmonth",
    "Harvestmonth",
    "Autumnmonth",
    "Fademonth",
    "Frostmonth",
    "Yearend",
)
_T026_DANGER_LEVELS = frozenset({"Low", "Medium", "High", "Very High"})
_T026_ABILITY_SKILL_CHECK = re.compile(
    r"^(?:Strength|Dexterity|Constitution|Intelligence|Wisdom|Charisma) "
    r"\(([^)]+)\) (DC [0-9]+: .+)$"
)


def _location_stub_ids(location_stubs: List[Dict[str, Any]]) -> List[str]:
    """Return a unique, ordered stub-ID list or reject the input contract."""
    ids = []
    for index, stub in enumerate(location_stubs):
        if not isinstance(stub, dict):
            raise ValueError(f"location stub {index} must be an object")
        location_id = stub.get("locationId")
        if not isinstance(location_id, str) or not location_id.strip():
            raise ValueError(f"location stub {index} has no useful locationId")
        ids.append(location_id)
    if len(ids) != len(set(ids)):
        raise ValueError("location stub IDs must be unique")
    return ids


def _t026_valid_cross_area_stub(area_connectivity: Any, area_connectivity_id: Any) -> bool:
    """Validate a stub's parallel cross-area arrays before trusting them (issue #159).

    Both must be lists of equal length containing only non-blank strings. Pairings
    are NOT inferred or repaired -- a malformed stub is a code-contract bug in the
    upstream compiler, surfaced by the caller, never a reason to keep model output.
    An empty pair ([], []) is valid (the classic path's uninitialized state).
    """
    if not isinstance(area_connectivity, list) or not isinstance(area_connectivity_id, list):
        return False
    if len(area_connectivity) != len(area_connectivity_id):
        return False
    for value in (*area_connectivity, *area_connectivity_id):
        if not isinstance(value, str) or not value.strip():
            return False
    return True


def _canonicalize_t026_stub_owned_fields(
    parsed: Any,
    location_stubs: List[Dict[str, Any]],
) -> Any:
    """Restore only absent trusted fields from the ordered stub contract.

    Location IDs are generated by the map builder and are not model-authored
    content.  T026 also requires the returned array to preserve stub order, so
    an omitted ID can be restored positionally when count and object shape are
    intact.  A present-but-conflicting ID is evidence that order may be wrong;
    in that case this function changes nothing and the existing envelope gate
    keeps the full-batch retry/fail-closed behavior.

    The map builder also assigns each stub's initial dangerLevel from the area
    configuration.  Preserve model-authored variation when present, but restore
    an omitted value from a schema-valid stub so a weak model cannot discard
    already-established upstream state.
    """
    corrected = copy.deepcopy(parsed)
    expected_ids = _location_stub_ids(location_stubs)
    if not isinstance(corrected, dict):
        return corrected
    locations = corrected.get("locations")
    if not isinstance(locations, list) or len(locations) != len(expected_ids):
        return corrected
    if not all(isinstance(location, dict) for location in locations):
        return corrected

    # Preflight every present value before restoring any item.  This prevents
    # a partial repair from obscuring a reordered or duplicated model result.
    for index, location in enumerate(locations):
        returned_id = location.get("locationId")
        if returned_id is None or (
            isinstance(returned_id, str) and not returned_id.strip()
        ):
            continue
        if not isinstance(returned_id, str) or (
            returned_id.strip().casefold() != expected_ids[index].casefold()
        ):
            return copy.deepcopy(parsed)

    restored_id_indexes = []
    restored_danger_indexes = []
    restored_coord_indexes = []
    restored_xarea_indexes = []
    malformed_xarea_indexes = []
    for index, location in enumerate(locations):
        if location.get("locationId") != expected_ids[index]:
            location["locationId"] = expected_ids[index]
            restored_id_indexes.append(index)

        # Coordinates are pure map geometry assigned by MapLayoutGenerator and
        # carried on the trusted stub; they are 100% code-owned, not creative
        # content. Identity==position is already guaranteed by the preflight
        # above, so a model coordinate that differs from the stub is a
        # hallucination (issue #128 class) for a location whose identity is
        # confirmed. Restore ALWAYS from the stub (unlike dangerLevel, which
        # permits model variation) so a coordinate drift can never ship.
        stub_coord = location_stubs[index].get("coordinates")
        if isinstance(stub_coord, str) and stub_coord.strip():
            if location.get("coordinates") != stub_coord:
                location["coordinates"] = stub_coord
                restored_coord_indexes.append(index)

        # areaConnectivity / areaConnectivityId are CODE-OWNED cross-area fields
        # (issue #159). Story-first compiles them into the stub
        # (compile_area_binding) and validates exact equality downstream; the
        # classic path leaves them empty on the stub and finalize is the sole
        # author (Step 4.55). The T026 model is (wrongly, pre-159-B) told to
        # author them and mislabels the parallel IDs as AREA ids, polluting the
        # field. Restore BOTH from the trusted stub on every index: classic ->
        # [] (model pollution cleared); story-first -> compiled links preserved
        # exactly, which satisfies the downstream exact-equality validator by
        # construction. Identity==position is already guaranteed by the preflight
        # above. A malformed STUB (parallel arrays unequal / non-string / blank)
        # is a code-contract bug we surface, never a reason to keep model output.
        stub_ac = location_stubs[index].get("areaConnectivity", [])
        stub_acid = location_stubs[index].get("areaConnectivityId", [])
        if not _t026_valid_cross_area_stub(stub_ac, stub_acid):
            malformed_xarea_indexes.append(index)
            stub_ac = stub_ac if isinstance(stub_ac, list) else []
            stub_acid = stub_acid if isinstance(stub_acid, list) else []
        if (location.get("areaConnectivity") != stub_ac
                or location.get("areaConnectivityId") != stub_acid):
            location["areaConnectivity"] = copy.deepcopy(stub_ac)
            location["areaConnectivityId"] = copy.deepcopy(stub_acid)
            restored_xarea_indexes.append(index)

        returned_danger = location.get("dangerLevel")
        stub_danger = location_stubs[index].get("dangerLevel")
        if (
            returned_danger is None
            or isinstance(returned_danger, str)
            and not returned_danger.strip()
        ) and stub_danger in _T026_DANGER_LEVELS:
            location["dangerLevel"] = stub_danger
            restored_danger_indexes.append(index)

    if restored_id_indexes:
        print(
            "WARNING: T026 restored "
            f"{len(restored_id_indexes)} omitted or format-only locationId "
            "value(s) from the trusted ordered stubs at indexes "
            f"{restored_id_indexes}."
        )
    if restored_danger_indexes:
        print(
            "WARNING: T026 restored "
            f"{len(restored_danger_indexes)} omitted or blank dangerLevel "
            "value(s) from the trusted ordered stubs at indexes "
            f"{restored_danger_indexes}."
        )
    if restored_coord_indexes:
        print(
            "WARNING: T026 corrected "
            f"{len(restored_coord_indexes)} model-drifted coordinates value(s) "
            "to the trusted map-owned stub coordinates at indexes "
            f"{restored_coord_indexes} (issue #128 class; coordinates are "
            "code-owned map geometry)."
        )
    if restored_xarea_indexes:
        print(
            "WARNING: T026 restored "
            f"{len(restored_xarea_indexes)} model-authored areaConnectivity/"
            "areaConnectivityId value(s) to the trusted code-owned stub at "
            f"indexes {restored_xarea_indexes} (issue #159; cross-area links "
            "are code-owned -- classic cleared to [], story-first preserved)."
        )
    if malformed_xarea_indexes:
        print(
            "WARNING: T026 encountered malformed cross-area STUB arrays "
            f"(unequal/non-string/blank) at indexes {malformed_xarea_indexes} "
            "(code-contract bug in the upstream stub; coerced to safe lists, "
            "did NOT trust model output)."
        )
    return corrected


def _canonicalize_t026_response_fields(
    parsed: Any,
    location_stubs: List[Dict[str, Any]],
) -> Any:
    """Apply the bounded stub-owned and mechanical T026 canonicalizers."""
    with_stub_fields = _canonicalize_t026_stub_owned_fields(
        parsed,
        location_stubs,
    )
    mechanical = _canonicalize_t026_mechanical_fields(with_stub_fields)
    # Item F: canonical lossless ASCII-typography normalization at the T026
    # generation response boundary (curly quotes -> straight, en/em dash -> -/--,
    # ellipsis -> ..., nbsp, arrows, Windows-1252/corrupted sequences). Windows
    # cp1252 consoles crash on non-ASCII, and several models stochastically emit
    # smart punctuation. Lossless map only -- never NFKD-strips or mangles a
    # proper noun. Residual non-ASCII (e.g. an accented name) is reported, never
    # silently deleted.
    normalized, replaced, residual = normalize_typography_deep(mechanical)
    if replaced:
        print(
            f"WARNING: T026 normalized {replaced} non-ASCII typography "
            "occurrence(s) to ASCII at the generation boundary."
        )
    if residual:
        print(
            "WARNING: T026 output retains residual non-ASCII after lossless "
            f"typography normalization at {residual[:8]} (Windows cp1252 crash "
            "risk); not deleted to avoid mangling names."
        )
    return normalized


def _canonicalize_t026_mechanical_fields(parsed: Any) -> Any:
    """Correct only unambiguous, machine-owned T026 syntax on a deep copy."""
    corrected = copy.deepcopy(parsed)
    if not isinstance(corrected, dict):
        return corrected
    locations = corrected.get("locations")
    if not isinstance(locations, list):
        return corrected

    for location in locations:
        if not isinstance(location, dict):
            continue
        location_id = location.get("locationId")

        # T026 creates a new module location before any play has occurred.
        # adventureSummary is living runtime history populated only after the
        # party leaves a location, so model-authored initial content is always
        # incorrect regardless of its type. Keep the required downstream field
        # while establishing its one valid initial state deterministically.
        location["adventureSummary"] = ""
        location["explorationState"] = {"status": "unvisited"}

        # Encounters are runtime-created records, not authored module content.
        # A fresh location has none: the shipped starter modules (e.g.
        # The_Thornwood_Watch, Keep_of_Doom) ship with empty encounters, and the
        # engine appends a dated encounter with the AUTHORITATIVE party-tracker
        # clock only when one actually occurs (core/managers/combat_manager.py
        # append; adv_summary/T015). Model-authored encounters carry invented
        # timestamps (Qwen produced day: 30 > the 28-day calendar, and years
        # 842/2024 vs the party's 1492) that are never the real clock but are fed
        # into DM narration context. Strip them deterministically so a weak model
        # can never inject a bad date or a phantom encounter into a new module.
        location["encounters"] = []

        checks = location.get("dcChecks")
        if isinstance(checks, list):
            for index, check in enumerate(checks):
                if not isinstance(check, str):
                    continue
                match = _T026_ABILITY_SKILL_CHECK.fullmatch(check)
                if match and match.group(1) in _T026_OFFICIAL_SKILLS:
                    checks[index] = f"{match.group(1)} {match.group(2)}"

        encounters = location.get("encounters")
        if not isinstance(encounters, list):
            continue
        for index, encounter in enumerate(encounters):
            if not isinstance(encounter, dict):
                continue
            if isinstance(location_id, str) and location_id:
                encounter["encounterId"] = f"{location_id}-E{index + 1}"
            world_conditions = encounter.get("worldConditions")
            if not isinstance(world_conditions, dict):
                continue
            month = world_conditions.get("month")
            if type(month) is int and 1 <= month <= len(_T026_CALENDAR_MONTHS):
                world_conditions["month"] = _T026_CALENDAR_MONTHS[month - 1]

    return corrected


@dataclass(frozen=True)
class _SchemaIssue:
    """One deterministic, user-prompt-safe schema issue."""

    path: str
    message: str


def _compact_issue_message(message: Any, limit: int = 240) -> str:
    """Bound model-derived validation text before it enters a retry prompt."""
    compact = " ".join(str(message).split())
    if len(compact) <= limit:
        return compact
    return compact[: limit - 3] + "..."


def _json_path(parts) -> str:
    """Render a jsonschema path deterministically as dotted/indexed JSON."""
    rendered = ""
    for part in parts:
        if isinstance(part, int):
            rendered += f"[{part}]"
        else:
            rendered += ("." if rendered else "") + str(part)
    return rendered or "$"


def _schema_issues(
    instance: Any,
    schema: Dict[str, Any],
    prefix=(),
) -> List[_SchemaIssue]:
    """Return all schema errors with stable paths and stable ordering."""
    validator = jsonschema.Draft7Validator(schema)
    errors = sorted(
        validator.iter_errors(instance),
        key=lambda error: (
            tuple(str(part) for part in error.absolute_path),
            str(error.validator),
            error.message,
        ),
    )
    issues = []
    for error in errors:
        path_parts = tuple(prefix) + tuple(error.absolute_path)
        if error.validator == "required" and isinstance(error.instance, dict):
            missing = sorted(
                key
                for key in error.validator_value
                if key not in error.instance
            )
            for key in missing:
                issues.append(
                    _SchemaIssue(
                        _json_path(path_parts + (key,)),
                        "required property is missing",
                    )
                )
            continue
        issues.append(
            _SchemaIssue(
                _json_path(path_parts),
                _compact_issue_message(error.message),
            )
        )
    return sorted(issues, key=lambda issue: (issue.path, issue.message))


def _format_schema_issues(issues: List[_SchemaIssue], limit: int = 24) -> str:
    """Compact schema feedback without embedding the full model response."""
    shown = issues[:limit]
    rendered = "; ".join(
        f"{issue.path}: {issue.message}" for issue in shown
    )
    if len(issues) > limit:
        rendered += f"; ... {len(issues) - limit} additional issue(s)"
    return rendered


def _validate_location_envelope(
    parsed: Any,
    location_stubs: List[Dict[str, Any]],
) -> List[Dict[str, Any]]:
    """Validate the structure that makes positional replacement trustworthy."""
    expected_ids = _location_stub_ids(location_stubs)
    if not isinstance(parsed, dict):
        raise ValueError("$: location batch must be a JSON object")

    locations = parsed.get("locations")
    if not isinstance(locations, list):
        raise ValueError("locations: required array is missing or invalid")
    if len(locations) != len(expected_ids):
        raise ValueError(
            f"locations: expected exactly {len(expected_ids)} item(s), "
            f"got {len(locations)}"
        )
    for index, location in enumerate(locations):
        if not isinstance(location, dict):
            raise ValueError(f"locations[{index}]: location must be an object")
        returned_id = location.get("locationId")
        if returned_id != expected_ids[index]:
            returned_display = _compact_issue_message(repr(returned_id))
            raise ValueError(
                "locationId order mismatch at "
                f"locations[{index}].locationId: expected "
                f"{expected_ids[index]!r}, got {returned_display}"
            )
    return locations


def _location_item_schema(schema: Dict[str, Any]) -> Dict[str, Any]:
    """Extract a location schema, tolerating minimal unit-test schemas."""
    try:
        item_schema = schema["properties"]["locations"]["items"]
    except (KeyError, TypeError):
        return {}
    return item_schema if isinstance(item_schema, dict) else {}


def _invalid_location_issues(
    locations: List[Dict[str, Any]],
    schema: Dict[str, Any],
) -> Dict[int, List[_SchemaIssue]]:
    """Map invalid batch indexes to deterministic schema issues."""
    item_schema = _location_item_schema(schema)
    invalid = {}
    for index, location in enumerate(locations):
        issues = _schema_issues(
            location,
            item_schema,
            prefix=("locations", index),
        )
        if issues:
            invalid[index] = issues
    return invalid


def _schema_with_exact_location_count(
    schema: Dict[str, Any],
    expected_count: int,
) -> Dict[str, Any]:
    """Deep-copy a response schema and constrain only its locations count."""
    constrained = copy.deepcopy(schema)
    try:
        locations_schema = constrained["properties"]["locations"]
    except (KeyError, TypeError):
        return constrained
    if isinstance(locations_schema, dict):
        locations_schema["minItems"] = expected_count
        locations_schema["maxItems"] = expected_count
    return constrained


def _strict_openai_schema(schema: Any) -> Any:
    """Return the OpenAI strict-output subset without mutating the source."""
    if isinstance(schema, list):
        return [_strict_openai_schema(value) for value in schema]
    if not isinstance(schema, dict):
        return copy.deepcopy(schema)

    strict = {}
    for key, value in schema.items():
        if key in {"$schema", "examples"}:
            continue
        strict[key] = _strict_openai_schema(value)
    if strict.get("type") == "object" or "properties" in strict:
        strict["additionalProperties"] = False
        # OpenAI strict structured output requires every declared property at
        # every object level to appear in ``required``. Optionality in that
        # dialect is expressed by nullable types, not by omitting the key.
        # T026 canonicalizes runtime-owned optional fields after generation.
        strict["required"] = sorted(strict.get("properties", {}))
    return strict


def _t026_request_options(
    provider: str,
    main_cfg: Dict[str, Any],
    schema: Dict[str, Any],
    expected_count: int,
):
    """Build provider-native output controls for one T026 semantic call."""
    constrained = _schema_with_exact_location_count(schema, expected_count)
    extra_params = {
        key: value for key, value in main_cfg.items() if key != "model"
    }

    if provider in {"openai", "legacy", "codex_oauth"}:
        response_format = {
            "type": "json_schema",
            "json_schema": {
                "name": "t026_location_batch",
                "strict": True,
                "schema": _strict_openai_schema(constrained),
            },
        }
    elif provider == "gemini":
        # T026 requires complete objects, unlike partial-delta callsites that
        # deliberately use the converter's historical defaults.
        extra_params["response_schema"] = convert_to_gemini_schema(
            constrained,
            preserve_required=True,
            preserve_constraints=True,
        )
        response_format = {"type": "json_object"}
    elif provider == "lmstudio":
        # Local OpenAI-compatible servers disagree on schema-format support.
        # Explicitly use prompt-enforced JSON plus the same fail-closed local
        # validator. This is a capability policy, not an extra semantic retry.
        response_format = None
    else:
        raise ValueError(f"unsupported T026 provider: {provider}")

    return response_format, extra_params


class LocationBatchReasoningContentError(ValueError):
    """T026 received provider reasoning in the JSON content channel."""


_T026_REASONING_CONTENT_MESSAGE = (
    "$: model reasoning appeared in response content before the JSON. "
    "For LM Studio, enable separation of reasoning_content and content, "
    "or disable model thinking for this model/template."
)


def _parse_t026_response(raw: Any) -> Dict[str, Any]:
    """Parse one model response with a bounded, deterministic error message."""
    if not isinstance(raw, str):
        raise ValueError("$: response content must be a JSON string")

    # Some OpenAI-compatible local models occasionally wrap an otherwise valid
    # JSON response in one Markdown JSON fence despite the prompt contract.
    # Accept only a single complete outer fence with whitespace outside it.
    # This deliberately does not extract JSON from commentary, multiple code
    # blocks, or a partial fence, so the downstream fail-closed contract stays
    # intact.
    fenced = re.fullmatch(
        r"\s*```json[ \t]*\r?\n(?P<body>.*?)\r?\n```\s*",
        raw,
        flags=re.IGNORECASE | re.DOTALL,
    )
    content = fenced.group("body") if fenced else raw

    if re.match(r"<think(?:\s[^>]*)?>", content.lstrip(), flags=re.IGNORECASE):
        raise LocationBatchReasoningContentError(
            _T026_REASONING_CONTENT_MESSAGE
        )
    try:
        parsed = json.loads(content)
    except json.JSONDecodeError as exc:
        raise ValueError(
            f"$: malformed JSON at line {exc.lineno}, column {exc.colno}"
        ) from exc
    if not isinstance(parsed, dict):
        raise ValueError("$: location batch must be a JSON object")
    return parsed


class LocationBatchCapacityError(RuntimeError):
    """T026 stopped because the selected model exhausted request capacity."""


_T026_CAPACITY_MESSAGE = (
    "Location generation stopped because the selected model reached its "
    "output or context capacity. No invalid location batch was saved. "
    "Increase the model's context/output limit, reduce the module size, or "
    "choose another model."
)

_T026_INVALID_RESPONSE_MESSAGE = (
    "Location batch generation returned invalid JSON or contract data after "
    "2 attempts. The selected model could not produce the required location "
    "data. No invalid location batch was saved. Retry, reconfigure the local "
    "model, or select another model."
)


def _is_capacity_finish_reason(reason: Any) -> bool:
    """Recognize explicit capacity stops without guessing from content."""
    return isinstance(reason, str) and reason.strip().lower() in {
        "length",
        "max_tokens",
    }


def _is_structured_context_limit_error(
    error: api_client.ProviderCallError,
) -> bool:
    """Recognize explicit context-limit codes from a provider exception."""
    original = getattr(error, "original_error", None)
    codes = [getattr(original, "code", None)]
    body = getattr(original, "body", None)
    if isinstance(body, dict):
        codes.append(body.get("code"))
        nested = body.get("error")
        if isinstance(nested, dict):
            codes.append(nested.get("code"))
    known_codes = {
        "context_length_exceeded",
        "context_window_exceeded",
        "max_context_length",
    }
    return any(
        isinstance(code, str) and code.strip().lower() in known_codes
        for code in codes
    )


def _validate_location_batch_contract(
    parsed: Any,
    location_stubs: List[Dict[str, Any]],
    schema: Dict[str, Any],
) -> Dict[str, Any]:
    """Final T026 schema/count/ID/order gate; return an ownership-safe copy."""
    _validate_location_envelope(parsed, location_stubs)
    issues = _schema_issues(parsed, schema)
    if issues:
        raise ValueError(
            f"schema validation failed: {_format_schema_issues(issues)}"
        )
    return copy.deepcopy(parsed)


@dataclass
class LocationPromptGuide:
    """Detailed prompts and examples for each location field"""
    
    name: str = """
    Location names should be evocative and specific to their purpose.
    They should hint at what players might find or experience.
    
    Examples by type:
    - Cave Entrance: "The Whispering Threshold", "Maw of Shadows"
    - Chamber: "Hall of Echoing Stone", "The Crystal Sanctum"  
    - Corridor: "The Winding Descent", "Passage of Whispers"
    - Throne Room: "Court of the Fallen King", "Ember Throne Chamber"
    
    Format: 2-5 words, capitalize major words
    Style: Atmospheric, hints at location's nature
    """
    
    type: str = """
    Location type defines its primary function and layout.
    Must match the area's theme (dungeon, wilderness, town, etc.)
    
    Dungeon types:
    - entrance, corridor, chamber, hall, vault, shrine, prison, 
      laboratory, throne room, treasure room, crypt, library
    
    Wilderness types:
    - clearing, grove, cave, ravine, hilltop, riverside, ruins, 
      campsite, crossroads, landmark, den, nest
    
    Town types:
    - square, market, tavern, shop, temple, guild, residence, 
      gate, warehouse, barracks, dock, alley
    
    Choose based on location's role in the adventure.
    """
    
    description: str = """
    The main description paints a vivid picture for players.
    Include sensory details and atmosphere.
    
    Structure (3-5 sentences):
    1. Overall impression and size
    2. Key visual features  
    3. Atmospheric details (sounds, smells, temperature)
    4. Notable objects or areas of interest
    5. Hints at danger or opportunity
    
    Example:
    "The chamber stretches thirty feet across, its vaulted ceiling 
    disappearing into darkness above. Ancient stone pillars, carved 
    with worn dwarven runes, support the weight of centuries. A musty 
    smell mingles with the faint scent of sulfur, while water drips 
    steadily from somewhere in the shadows. Against the far wall, a 
    massive stone door bears the seal of a hammer wreathed in flames."
    
    Length: 3-5 sentences
    Style: Present tense, immersive, specific details
    """
    
    dmInstructions: str = """
    DM instructions provide practical running advice not obvious to players.
    Include mechanics, secrets, and pacing guidance.
    
    Should cover:
    - Hidden elements (secret doors, traps, treasures)
    - Skill check DCs and their results
    - Combat tactics for inhabitants
    - Environmental hazards or effects
    - Connections to the larger plot
    - Timing considerations
    
    Example:
    "The pillars conceal pressure plates (DC 15 Perception to notice). 
    Triggering one releases poison darts (DC 13 Dex save, 2d4 poison 
    damage). The sealed door requires the proper ritual phrase or DC 20 
    Strength to force. Behind it lies the forge guardian, which activates 
    if the seal is broken violently. The sulfur smell intensifies near 
    the secret passage (DC 18 Investigation to find) leading to area R07."
    
    Length: 3-5 sentences
    Style: Mechanical, specific DCs and effects
    """
    
    accessibility: str = """
    How easily can this location be accessed?
    Describes physical entry/exit challenges.
    
    Examples:
    - "Open archway, easily accessible"
    - "Narrow passage requiring squeeze (DC 12 Athletics)"
    - "Locked iron door (DC 15 Thieves' Tools)"
    - "Hidden entrance behind waterfall (DC 16 Perception)"
    - "Rope bridge over chasm (DC 10 Acrobatics)"
    
    Include: Physical barriers, skill checks, special requirements
    """
    
    npcs: str = """
    NPCs found in this location (if any).
    List inhabitants with their disposition and purpose.
    
    Each NPC entry should have:
    - name: Their name or identifier
    - description: Brief physical/personality note
    - attitude: hostile, neutral, friendly, cautious, etc.
    
    Example:
    {
        "name": "Grimtooth the Gatekeeper",
        "description": "A scarred hobgoblin veteran with a missing eye",
        "attitude": "hostile"
    }
    
    NPCs should:
    - Fit the location's purpose
    - Have clear motivations
    - Connect to plot/quests when possible
    
    Note: Your main.py will generate full stats when needed.
    """
    
    monsters: str = """
    Creatures that may be encountered here.
    Include quantity ranges for scalability.
    
    CRITICAL NAMING REQUIREMENT:
    - Use SINGULAR names ONLY (e.g., "goblin", "skeleton", "orc")
    - NEVER use plural names (e.g., "goblins", "skeletons", "orcs")
    - Each monster entry represents a single creature type, not a group
    - Multiple creatures are handled through quantity, not plural names
    
    Each monster entry needs:
    - name: Creature type in SINGULAR form (e.g., "goblin", "dire wolf")
    - quantity: min/max range for group size
    
    Example:
    {
        "name": "stone guardian",
        "quantity": {"min": 1, "max": 2}
    }
    
    Consider:
    - Appropriate CR for area's danger level
    - Logical inhabitants for location type
    - Environmental fit (no fish in desert)
    - Plot connections (cultists in evil temple)
    
    Note: Combat stats generated separately by your system.
    """
    
    plotHooks: str = """
    Story elements that draw players deeper into the adventure.
    Brief hints that connect to larger plot or offer side quests.
    
    Examples:
    - "Fresh blood trails lead toward the eastern passage"
    - "A journal page mentions 'the ceremony at midnight'"
    - "Strange symbols match those from the stolen artifact"
    - "Voices echo from behind the sealed door"
    
    Format: 1-2 sentence hints or observations
    Quantity: 1-3 hooks per location
    Purpose: Guide players, provide clues, create tension
    """
    
    lootTable: str = """
    Potential treasures found through search or victory.
    Mix of monetary and useful items.
    
    Categories:
    - Currency: "50 gold pieces", "ancient silver coins"
    - Consumables: "healing potion", "scroll of fireball"
    - Equipment: "masterwork longsword", "boots of elvenkind"
    - Plot items: "crystal key", "coded message"
    - Mundane: "silk rope", "adventurer's kit"
    
    Balance value with danger level and effort required.
    Important items should require investigation or risk.
    """
    
    dangerLevel: str = """
    Overall threat assessment for the location.
    Must be one of: "Low", "Medium", "High", "Very High"
    
    Factors:
    - Low: Safe rest area, friendly NPCs, no traps
    - Medium: Some monsters, minor traps, environmental hazards
    - High: Deadly creatures, dangerous traps, hostile NPCs
    - Very High: Boss monsters, lethal traps, extreme conditions
    
    Should match the area's overall danger level but can vary.
    """
    
    connectivity: str = """
    Direct physical connections to other locations.
    List locationIds of adjacent rooms/areas.
    
    Examples: ["R01", "R03", "R07"]
    
    Connections should:
    - Match the map layout
    - Make logical sense (doors, passages, stairs)
    - Create interesting navigation choices
    - Allow multiple paths when possible
    """
    
    traps: str = """
    Mechanical or magical hazards in the location.
    Each trap needs detection, disabling, and effect details.
    
    Required fields:
    - name: Descriptive identifier
    - description: How it works and appears
    - detectDC: Perception/Investigation check
    - disableDC: Thieves' Tools/Arcana check
    - triggerDC: Save if triggered (or "automatic")
    - damage: Effect when triggered
    
    Example:
    {
        "name": "Flame Jet Trap",
        "description": "Hidden nozzles spray fire when triggered",
        "detectDC": 15,
        "disableDC": 13,
        "triggerDC": 14,
        "damage": "3d6 fire damage, DC 14 Dex save for half"
    }
    
    Balance lethality with level appropriateness.
    """
    
    features: str = """
    Notable non-trap elements that define the location.
    Interactive or descriptive elements.
    
    Each feature needs:
    - name: What to call it
    - description: What it looks like and does
    
    Examples:
    - Ancient altar (can be investigated)
    - Collapsed ceiling (difficult terrain)
    - Underground stream (water source)
    - Magical fountain (healing properties)
    - Crystal formation (valuable but dangerous)
    
    Features add character and opportunities for interaction.
    """
    
    dcChecks: str = """
    Skill challenges available in the location.
    Format: "SkillName DC XX: Result description"
    
    Examples:
    - "Perception DC 15: Notice the secret door behind the tapestry"
    - "Investigation DC 12: Find the hidden compartment in the altar"
    - "Athletics DC 18: Climb the crumbling wall to the upper level"
    - "Arcana DC 16: Identify the magical aura around the crystals"
    - "History DC 14: Recognize the dwarven clan symbols"
    
    Provide 2-4 meaningful checks per location.
    Results should offer advantages or information.
    """
    
    encounters: str = """
    Encounters are runtime-created history records, not authored module content.
    A newly created, unplayed location has none.

    Return encounters as an empty array: [].
    Do NOT invent encounter history, encounterIds, dates, times, years, months,
    or days. The engine creates dated encounter records at runtime, from the
    party's authoritative clock, only when an encounter actually occurs.
    Put possible future scenes in dmInstructions, plotHooks, or monsters instead.
    """
    
    doors: str = """
    Detailed information about entrances and exits.
    Each door/passage needs security and condition details.
    
    Required fields:
    - name: Identifier (e.g., "North Door", "Secret Panel")
    - description: Physical appearance and material
    - type: Regular, secret, portcullis, magical, etc.
    - locked: true/false
    - lockDC: Difficulty to pick (0 if not locked)
    - breakDC: Difficulty to force open
    - keyname: What opens it (if applicable)
    - trapped: true/false
    - trap: Trap details if trapped
    
    Example:
    {
        "name": "Iron-bound Oak Door",
        "description": "Massive door reinforced with iron bands",
        "type": "heavy",
        "locked": true,
        "lockDC": 15,
        "breakDC": 20,
        "keyname": "Guardian's Key",
        "trapped": false,
        "trap": ""
    }
    
    Doors control flow and present challenges.
    """
    
    areaConnectivity: str = """
    CODE-OWNED. Do NOT author this. Cross-area connections are assigned
    deterministically by the module builder from the plot route after all
    locations are generated. Copy the exact value from the supplied stub
    (usually []). Never add, remove, rename, or reinterpret it.
    """

    areaConnectivityId: str = """
    CODE-OWNED. Do NOT author this. It holds destination LOCATION IDs (parallel
    by index with areaConnectivity's area names) and is assigned by the module
    builder from the plot route. Copy the exact value from the supplied stub
    (usually []). It is NOT a list of area IDs.

    Used by system for area transitions.
    """

# --- T026 surgical field repair (issue #134 fail-forward ladder) --------------
# When the model omits or malforms a field on an otherwise-good location, fix ONLY
# that field instead of regenerating the whole location (which re-rolls the
# stochastic model and can drop a different field or rewrite good content).
#   * Mechanical fields  -> code fills from the trusted stub or a fixed runtime
#                           default (no model call, one correct answer).
#   * Creative fields    -> re-ask the model for JUST that field's value
#                           (generate_field), seeded with the location's own good
#                           content; code splices the value back in.
#   * Creative that still -> a minimal schema-valid floor so the build never
#     fails (rare)          aborts; the field name is returned so the pipeline can
#                           flag the location for the module doctor to enrich.
_T026_STRUCTURAL_STUB_FIELDS = (
    "locationId", "name", "type", "coordinates", "connectivity",
    "areaConnectivity", "areaConnectivityId",
)
_T026_RUNTIME_FIELD_DEFAULTS = {
    "encounters": [],
    "adventureSummary": "",
    "explorationState": {"status": "unvisited"},
}


def _t026_top_field(path: str) -> str:
    """Reduce a schema issue path to its top location field.

    Handles the batch prefix ('locations[3].monsters[0].quantity' -> 'monsters')
    and unprefixed paths ('description' -> 'description').
    """
    if path.startswith("locations["):
        close = path.find("]")
        if close != -1:
            path = path[close + 1:].lstrip(".")
    for separator in (".", "["):
        cut = path.find(separator)
        if cut != -1:
            path = path[:cut]
    return path


def _t026_creative_floor(field_schema: Dict[str, Any]) -> Any:
    """A minimal schema-valid value for a creative field the model could not fill."""
    kind = field_schema.get("type") if isinstance(field_schema, dict) else None
    if kind == "array":
        return []
    if kind == "object":
        return {}
    if kind in ("integer", "number"):
        return field_schema.get("minimum", 0) if isinstance(field_schema, dict) else 0
    return "To be detailed by the module doctor."


def _t026_surgical_repair_location(gen, location, stub, issues, item_schema, context):
    """Repair ONLY the broken fields of one location, preserving accepted content.

    Returns (fixed_location, floored_fields). The caller re-validates; any field in
    floored_fields was code-filled as a last resort and should be flagged for the
    module doctor.
    """
    fixed = copy.deepcopy(location)
    props = item_schema.get("properties", {}) if isinstance(item_schema, dict) else {}
    floored = []
    handled = set()
    for issue in issues:
        field = _t026_top_field(issue.path)
        if not field or field in handled:
            continue
        handled.add(field)
        if field in _T026_STRUCTURAL_STUB_FIELDS and isinstance(stub, dict) and field in stub:
            fixed[field] = copy.deepcopy(stub[field])            # trusted structure, code-owned
        elif field in _T026_RUNTIME_FIELD_DEFAULTS:
            fixed[field] = copy.deepcopy(_T026_RUNTIME_FIELD_DEFAULTS[field])
        else:
            field_schema = props.get(field, {"type": "string"})
            try:
                fixed[field] = gen.generate_field(field, field_schema, context)   # surgical agentic
            except Exception:
                fixed[field] = _t026_creative_floor(field_schema)  # last-resort valid floor
                floored.append(field)
    return fixed, floored


class LocationGenerator:
    def __init__(self):
        self.prompt_guide = LocationPromptGuide()
        # Runtime schema -- the live gameplay contract. Used to VALIDATE every
        # accepted T026 result before publishing (encounters allowed, runtime
        # populates them). Never weakened.
        self.schema = self.load_schema()
        # Generation schema -- a clean duplicate of the runtime schema with the
        # runtime-owned encounter/date-time template removed. Used only to
        # CONSTRAIN the model-facing request so schema-honoring providers
        # (OpenAI strict, Gemini response_schema) are never shown a dated
        # encounter shape to imitate. See schemas/loca_generation_schema.json.
        self.generation_schema = self.load_generation_schema()

    def load_schema(self) -> Dict[str, Any]:
        """Load the runtime location schema for validation"""
        with open("schemas/loca_schema.json", "r") as f:
            return json.load(f)

    def load_generation_schema(self) -> Dict[str, Any]:
        """Load the generation-only location schema for model-facing requests"""
        with open("schemas/loca_generation_schema.json", "r") as f:
            return json.load(f)
    
    def generate_field(self, field_path: str, schema_info: Dict[str, Any], 
                      context: Dict[str, Any]) -> Any:
        """Generate content for a specific field"""
        field_name = field_path.split(".")[-1]
        guide_attr = field_name
        
        # Handle nested fields with underscores
        if "." in field_path:
            guide_attr = field_path.replace(".", "_")
        
        guide_text = getattr(self.prompt_guide, guide_attr, "")
        
        prompt = f"""Generate content for the '{field_path}' field of a 5e location.

Field Schema:
{json.dumps(schema_info, indent=2)}

Detailed Guidelines:
{guide_text}

Context:
{json.dumps(context.to_dict() if hasattr(context, 'to_dict') else context, indent=2)}

Return ONLY the value for this field in the correct format.
For strings, return just the string.
For arrays, return just the array.
For objects, return just the object.
Use only standard ASCII characters -- no smart quotes, no em-dashes, no Unicode symbols.
"""

        from model_config import MODEL_PROVIDER
        if MODEL_PROVIDER == "openai":
            main_cfg = config.DM_MAIN_GPT52_NONE
        elif MODEL_PROVIDER == "gemini":
            main_cfg = config.DM_MAIN_GEMINI_PRO_LOW
        elif MODEL_PROVIDER == "lmstudio":
            main_cfg = config.DM_MAIN_LMSTUDIO
        else:  # legacy
            main_cfg = config.DM_MAIN_LEGACY

        response = capture_and_fanout("T025", api_client.create_completion,
            _request_provider=MODEL_PROVIDER,
            messages=[
                {"role": "system", "content": "You are an expert 5e location designer. Return only the requested data in the exact format needed."},
                {"role": "user", "content": prompt}
            ],
            model=main_cfg["model"],
            temperature=0.7,
            response_format=None,
            **{k: v for k, v in main_cfg.items() if k != "model"})

        content = response.choices[0].message.content.strip()
        if content.startswith("```") and content.endswith("```"):
            content = content.split("\n", 1)[-1].rsplit("```", 1)[0].strip()

        expected_type = schema_info.get("type") if isinstance(schema_info, dict) else None
        if expected_type == "string":
            value = content
        else:
            try:
                value = json.loads(content)
            except json.JSONDecodeError as exc:
                raise ValueError(
                    f"T025 returned invalid JSON for {field_path}"
                ) from exc

        try:
            jsonschema.validate(value, schema_info)
        except jsonschema.ValidationError as exc:
            raise ValueError(
                f"T025 response violates the schema for {field_path}: {exc.message}"
            ) from exc
        return value

    def generate_location_batch(self, 
                               area_data: Dict[str, Any],
                               plot_data: Dict[str, Any],
                               module_data: Dict[str, Any],
                               location_stubs: List[Dict[str, Any]],
                               context=None,
                               excluded_names=None,
                               context_header: str = "") -> Dict[str, Any]:
        """Generate all locations for an area in one go for better coherence"""
        
        generation_context = {
            "module": {
                "name": module_data.get("moduleName", ""),
                "description": module_data.get("moduleDescription", ""),
                "theme": module_data.get("worldSettings", {}).get("era", ""),
                "magicLevel": module_data.get("worldSettings", {}).get("magicPrevalence", "")
            },
            "area": {
                "name": area_data.get("areaName", ""),
                "type": area_data.get("areaType", "dungeon"),
                "description": area_data.get("areaDescription", ""),
                "dangerLevel": area_data.get("dangerLevel", "medium"),
                "recommendedLevel": area_data.get("recommendedLevel", 1)
            },
            "plot": {
                "title": plot_data.get("plotTitle", ""),
                "objective": plot_data.get("mainObjective", ""),
                "currentStage": plot_data.get("plotPoints", [{}])[0].get("description", "") if plot_data.get("plotPoints") else ""
            }
        }
        
        # Add validation requirements if context provided
        validation_prompt = ""
        if context:
            validation_prompt = context.get_validation_prompt()
        
        # Add party name exclusion to prompt
        party_exclusion_prompt = ""
        if excluded_names:
            party_exclusion_prompt = f"""
CRITICAL: Do NOT use these names for NPCs as they are existing party members: {', '.join(excluded_names)}
Create entirely different names that don't conflict with or resemble these party member names.
Avoid any variations, surnames, or titles using these names.
"""

        # Shared by full generation and targeted repair. Cardinality and the
        # selected stubs stay outside this block so each prompt has one clear
        # output contract.
        location_contract_prompt = f"""Each returned location must include ALL required fields from the location schema.

Ensure locations:
1. Connect logically based on the map layout
2. Support the plot's needs (place key items, NPCs, and clues appropriately)
3. If a location stub already has an NPC entry (like a pre-placed antagonist), you MUST include that NPC. You can enhance their description, but their name and presence are mandatory
4. Vary in purpose and challenge
5. Include a mix of combat, exploration, and roleplay opportunities
6. Feel cohesive as part of the same {area_data.get('areaType', 'area')}

CRITICAL COMPLETE LOCATION CHECKLIST -- field names and nesting must match EXACTLY:
- Every location object requires: name, type, description, dmInstructions,
  locationId, coordinates, accessibility, npcs, monsters, plotHooks,
  lootTable, dangerLevel, connectivity, areaConnectivity,
  areaConnectivityId, traps, features, dcChecks, encounters,
  adventureSummary, and doors. Never omit a required field; use [] for an
  empty array and "" for an intentionally empty string.
- "adventureSummary" must be exactly "". This is a newly created module, so
  no player events have occurred yet; runtime departure processing populates
  this living-history field later.
- "npcs" (NOT "notableNPCs") is an array of complete objects. Every NPC
  requires name (string), description (string), and attitude (string).
- "monsters" (NOT "creatures") is an array of complete objects. Every
  monster requires name (string) and quantity (object); quantity requires
  min (integer, 0 or greater) and max (integer, 1 or greater).
- "plotHooks", "lootTable" (NOT "items"), "connectivity",
  "areaConnectivity", "areaConnectivityId", and "dcChecks" are arrays of
  strings, never arrays of objects.
- Every trap requires name (string), description (string), detectDC
  (integer), disableDC (integer), triggerDC (integer), and damage (string).
- Every feature requires name (string) and description (string).
- "encounters" must be exactly []. This is a newly created, unplayed location,
  so no encounters have occurred yet; the engine creates dated encounter records
  at runtime when one actually occurs. Do NOT invent encounter history,
  encounterIds, dates, times, years, months, or days. Put possible future scenes
  in dmInstructions, plotHooks, or monsters.
- Every door requires name, description, type, locked, lockDC, breakDC,
  keyname, trapped, and trap, using the types listed below.
- "dcChecks" entries begin with an official skill or ability name only and use
  "SkillOrAbility DC XX: Description". Use "Arcana DC 13:", not
  "Intelligence (Arcana) DC 13:". Valid multiword examples include
  "Animal Handling DC 12:" and "Sleight of Hand DC 15:". A raw ability
  check such as "Wisdom DC 14:" is also valid.
- SRD 5.2.1 check naming: an ability check is named for one of the six
  abilities; a skill or tool proficiency can apply to that check. This output
  contract also permits one official skill as shorthand, but the label before
  "DC" must be exactly ONE of: Strength, Dexterity, Constitution,
  Intelligence, Wisdom, Charisma, Acrobatics, Animal Handling, Arcana,
  Athletics, Deception, History, Insight, Intimidation, Investigation,
  Medicine, Nature, Perception, Performance, Persuasion, Religion,
  Sleight of Hand, Stealth, or Survival.
- Never put a slash, "or", parentheses, or a tool name in the check label. If
  alternate skills or a tool proficiency apply, use the governing ability as
  the label and state the applicable proficiencies in the description. For
  example: "Strength DC 13: Cross the broken stairs; Acrobatics or Athletics
  proficiency applies." Or: "Intelligence DC 16: Repair the timing gauge;
  Tinker's Tools proficiency applies."
- "coordinates" uses "X<number>Y<number>"; "dangerLevel" is exactly one of
  "Low", "Medium", "High", or "Very High".
- Use "dmInstructions" for DM-only notes and "plotHooks" (NOT "clues")
  for story hooks.

DOOR STRUCTURE: Every door must have ALL these fields:
- name (string): e.g., "North Door", "Secret Panel"
- description (string): physical appearance
- type (string): e.g., "regular", "secret", "heavy"
- locked (boolean): true or false
- lockDC (integer): difficulty to pick (0 if not locked)
- breakDC (integer): difficulty to force open
- keyname (string): what opens it (empty string if none)
- trapped (boolean): true or false
- trap (string): trap description (empty string if not trapped)

AREA CONNECTIVITY RULES:
- "areaConnectivity" and "areaConnectivityId" are CODE-OWNED cross-area fields.
  Do NOT author them. Copy the exact values from each supplied stub (usually []).
  The module builder assigns all cross-area connections deterministically from the
  plot route after generation; anything you put here is discarded. Note that
  "areaConnectivityId" holds destination LOCATION IDs, not area IDs.

Check the location schema carefully for all required fields.
Use only standard ASCII characters -- no smart quotes, no em-dashes, and no
Unicode symbols.

CRITICAL: You MUST use the exact locationId values from the stubs provided.
Do not change, rename, or replace any locationId. The map grid was generated
with these specific IDs and the entire module wiring (connectivity, plot
references, area cross-links) depends on them. Renaming an ID -- for example
returning "R01" when the stub says "A01" -- breaks the module.
"""

        batch_context = copy.deepcopy(generation_context)
        batch_context["locationStubs"] = copy.deepcopy(location_stubs)

        # Generate all locations with a single comprehensive prompt.
        batch_prompt = f"""{context_header}Generate detailed 5e locations for {area_data.get('areaName', 'this area')}.

{party_exclusion_prompt}

Context:
{json.dumps(batch_context, indent=2)}

{validation_prompt}

For each location stub provided, generate complete location data following the schema.
Return one JSON object with a "locations" array containing exactly
{len(location_stubs)} complete location object(s), in the provided stub order.
Return no commentary or Markdown.

{location_contract_prompt}
"""

        from model_config import get_provider, resolve_callsite_config
        # T026's measured Luna selection and every non-OpenAI compatibility
        # branch come from the same registry used by capture tooling.
        provider = get_provider()
        main_cfg = resolve_callsite_config("T026", provider)

        # Reject ambiguous stub input before spending a model request.
        _location_stub_ids(location_stubs)

        def _semantic_call(prompt: str, expected_count: int):
            # Constrain the model-facing request with the GENERATION schema
            # (no encounter/date-time template). The accepted result is still
            # validated against the runtime self.schema below.
            response_format, extra_params = _t026_request_options(
                provider,
                main_cfg,
                self.generation_schema,
                expected_count,
            )
            try:
                response = capture_and_fanout(
                    "T026",
                    api_client.create_completion,
                    _request_provider=provider,
                    messages=[
                        {
                            "role": "system",
                            "content": (
                                "You are an expert 5e dungeon designer creating "
                                "cohesive, interconnected locations."
                            ),
                        },
                        {"role": "user", "content": prompt},
                    ],
                    model=main_cfg["model"],
                    # temperature is passed uniformly like every sibling callsite;
                    # create_completion's _enforce_provider_constraints strips it
                    # automatically for gpt-5.x (non-mini) at reasoning > none
                    # (e.g. luna|high), so no callsite-level gating is needed.
                    temperature=0.8,
                    response_format=response_format,
                    **extra_params,
                )
            except api_client.ProviderEmptyResponse as exc:
                if _is_capacity_finish_reason(exc.finish_reason):
                    raise LocationBatchCapacityError(
                        _T026_CAPACITY_MESSAGE
                    ) from exc
                # An unexplained empty response is a content failure. Converting
                # it to ValueError deliberately routes it through T026's one
                # existing semantic retry rather than adding another retry loop.
                raise ValueError("$: response contained no usable text") from exc
            except api_client.ProviderCallError as exc:
                if _is_structured_context_limit_error(exc):
                    raise LocationBatchCapacityError(
                        _T026_CAPACITY_MESSAGE
                    ) from exc
                raise

            finish_reason = getattr(response.choices[0], "finish_reason", None)
            if _is_capacity_finish_reason(finish_reason):
                raise LocationBatchCapacityError(_T026_CAPACITY_MESSAGE)
            return response

        def _full_retry(first_error: ValueError) -> Dict[str, Any]:
            retry_prompt = batch_prompt + f"""

FULL-BATCH CORRECTION REQUIRED (semantic call 2 of 2):
The first response could not be aligned safely with the requested stubs.
Deterministic validation error: {first_error}
Regenerate the COMPLETE batch. Return exactly {len(location_stubs)} complete
location objects in the original stub order with the exact original locationId
at every index. Reapply the complete field and nested-object checklist above.
Do not return commentary or Markdown.
"""
            try:
                retry_response = _semantic_call(
                    retry_prompt,
                    len(location_stubs),
                )
                retry_parsed = _canonicalize_t026_response_fields(
                    _parse_t026_response(
                        retry_response.choices[0].message.content
                    ),
                    location_stubs,
                )
                return _validate_location_batch_contract(
                    retry_parsed,
                    location_stubs,
                    self.schema,
                )
            except ValueError as retry_error:
                raise ValueError(
                    f"{_T026_INVALID_RESPONSE_MESSAGE} The full retry "
                    f"remained invalid: {retry_error}"
                ) from retry_error

        # Call 1 always requests the complete batch. No generated state escapes
        # until the final full schema/count/exact-ID/order gate succeeds.
        try:
            first_response = _semantic_call(
                batch_prompt,
                len(location_stubs),
            )
            first_parsed = _canonicalize_t026_response_fields(
                _parse_t026_response(
                    first_response.choices[0].message.content
                ),
                location_stubs,
            )
            first_locations = _validate_location_envelope(
                first_parsed,
                location_stubs,
            )
        except ValueError as first_error:
            print(
                "WARNING: T026 first response was not structurally safe for "
                f"targeted repair; using one full retry: {first_error}"
            )
            return _full_retry(first_error)

        invalid_by_index = _invalid_location_issues(
            first_locations,
            self.schema,
        )

        # Fail-forward ladder (issue #134): surgically repair ONLY the broken
        # field(s) of each otherwise-good location before any whole-location
        # regeneration. This preserves the model's accepted content -- mechanical
        # fields are code-filled from the trusted stub, creative fields are
        # re-asked one at a time (generate_field) and spliced back in, and a
        # creative field the model still cannot produce gets a minimal valid floor
        # flagged for the module doctor. Locations made valid drop out of the
        # whole-location repair set below, so a weak model's stochastic field
        # omission never aborts the build.
        if invalid_by_index:
            item_schema = _location_item_schema(self.schema)
            base_context = {
                "moduleName": module_data.get("moduleName", ""),
                "areaName": area_data.get("areaName", ""),
                "areaType": area_data.get("areaType", ""),
            }
            remaining_invalid = {}
            for index, issues in invalid_by_index.items():
                context = dict(base_context)
                context["stub"] = location_stubs[index]
                context["location"] = first_locations[index]
                repaired, floored = _t026_surgical_repair_location(
                    self, first_locations[index], location_stubs[index],
                    issues, item_schema, context,
                )
                still = _schema_issues(
                    repaired, item_schema, prefix=("locations", index)
                )
                if still:
                    remaining_invalid[index] = still
                else:
                    first_locations[index] = repaired
                    if floored:
                        print(
                            "WARNING: T026 surgical repair floor-filled "
                            f"{location_stubs[index].get('locationId')} fields "
                            f"{floored}; flag for module doctor enrichment"
                        )
            invalid_by_index = remaining_invalid

        if not invalid_by_index:
            try:
                return _validate_location_batch_contract(
                    first_parsed,
                    location_stubs,
                    self.schema,
                )
            except ValueError as first_error:
                # This covers root-level schema constraints not attributable to
                # a complete location. Positional replacement cannot fix it.
                print(
                    "WARNING: T026 first response failed the final root gate; "
                    f"using one full retry: {first_error}"
                )
                return _full_retry(first_error)

        # Count, object shape, location IDs, and order are trustworthy, so only
        # invalid locations may be replaced. Accepted siblings are deep-copied
        # and never included in the repair response contract.
        invalid_indexes = sorted(invalid_by_index)
        repair_stubs = [location_stubs[index] for index in invalid_indexes]
        repair_payload = []
        for index in invalid_indexes:
            location_issues = invalid_by_index[index]
            repair_payload.append(
                {
                    "batchIndex": index,
                    "expectedLocationId": location_stubs[index]["locationId"],
                    "stub": location_stubs[index],
                    "validationErrors": [
                        {"path": issue.path, "message": issue.message}
                        for issue in location_issues[:24]
                    ],
                    "additionalValidationErrorCount": max(
                        0,
                        len(location_issues) - 24,
                    ),
                }
            )

        repair_context = copy.deepcopy(generation_context)
        repair_context["locationStubs"] = copy.deepcopy(repair_stubs)

        repair_prompt = f"""{context_header}Repair invalid 5e locations for {area_data.get('areaName', 'this area')}.

{party_exclusion_prompt}

Context (only the stubs that require replacement):
{json.dumps(repair_context, indent=2)}

{validation_prompt}

{location_contract_prompt}

TARGETED COMPLETE-LOCATION REPLACEMENT (semantic call 2 of 2):
The first batch had trustworthy count, object shape, locationId values, and
order. Replace ONLY the invalid locations listed below. Each replacement must
be a COMPLETE location object satisfying every field and nested-object rule in
the full checklist above; do not send a patch or partial object.

Return one JSON object with a "locations" array containing exactly
{len(repair_stubs)} replacement object(s), in the listed order, with the exact
locationId values below:
{json.dumps(_location_stub_ids(repair_stubs))}
Do not include accepted sibling locations. Return no commentary or Markdown.

Invalid locations and deterministic validation paths:
{json.dumps(repair_payload, indent=2, sort_keys=True)}
"""

        try:
            repair_response = _semantic_call(
                repair_prompt,
                len(repair_stubs),
            )
            repair_parsed = _canonicalize_t026_response_fields(
                _parse_t026_response(
                    repair_response.choices[0].message.content
                ),
                repair_stubs,
            )
            validated_repair = _validate_location_batch_contract(
                repair_parsed,
                repair_stubs,
                self.schema,
            )
        except ValueError as repair_error:
            raise ValueError(
                f"{_T026_INVALID_RESPONSE_MESSAGE} The targeted repair "
                f"remained invalid: {repair_error}"
            ) from repair_error

        accepted_indexes = sorted(
            set(range(len(first_locations))) - set(invalid_indexes)
        )
        accepted_snapshots = {
            index: copy.deepcopy(first_locations[index])
            for index in accepted_indexes
        }
        merged = copy.deepcopy(first_parsed)
        replacements = validated_repair["locations"]
        for repair_index, batch_index in enumerate(invalid_indexes):
            merged["locations"][batch_index] = copy.deepcopy(
                replacements[repair_index]
            )

        for index, accepted in accepted_snapshots.items():
            if merged["locations"][index] != accepted:
                raise ValueError(
                    "T026 internal safety failure: accepted sibling "
                    f"{index} changed"
                )

        try:
            return _validate_location_batch_contract(
                merged,
                location_stubs,
                self.schema,
            )
        except ValueError as merged_error:
            raise ValueError(
                f"{_T026_INVALID_RESPONSE_MESSAGE} The targeted replacement "
                "produced a merged batch that "
                f"failed the final gate: {merged_error}"
            ) from merged_error
    
    def generate_locations(self,
                          area_data: Dict[str, Any],
                          plot_data: Dict[str, Any],
                          module_data: Dict[str, Any],
                          context=None,
                          excluded_names=None,
                          context_header: str = "") -> Dict[str, Any]:
        """Generate all locations for an area"""
        
        # Get location stubs from area data or create from map
        location_stubs = area_data.get("locations", [])
        
        if not location_stubs and "map" in area_data:
            # Create location stubs from map rooms
            location_stubs = []
            for room in area_data.get("map", {}).get("rooms", []):
                location_stub = {
                    "locationId": room["id"],
                    "name": room["name"],
                    "type": room["type"],
                    "connections": room["connections"],
                    "coordinates": room["coordinates"]
                }
                location_stubs.append(location_stub)
        
        if not location_stubs:
            print("DEBUG: [Location Generator] Warning: No location stubs or map found in area data")
            return {"locations": []}
        
        print(f"DEBUG: [Location Generator] Generating {len(location_stubs)} locations for {area_data.get('areaName', 'area')}...")
        
        # Generate all locations in batch
        location_data = self.generate_location_batch(
            area_data, plot_data, module_data, location_stubs, context, excluded_names, context_header)
        
        # Ensure each location has required fields and connections
        locations = location_data.get("locations", [])
        
        # Post-process to ensure consistency
        location_ids = set()
        name_to_id = {}  # issue #128: map location NAME -> locationId for resolution
        for loc in locations:
            if isinstance(loc, dict) and "locationId" in loc:
                location_ids.add(loc["locationId"])
                loc_name = loc.get("name")
                if loc_name:
                    name_to_id[loc_name] = loc["locationId"]

        for location in locations:
            # issue #128: guard against a malformed AI batch returning a non-dict
            # entry (e.g. a stray string) -- would otherwise crash on .get() below.
            if not isinstance(location, dict):
                print(f"WARNING: [Location Generator] Skipping non-dict location entry: {location}")
                continue
            # Validate connections exist
            raw_connectivity = location.get("connectivity", [])
            validated_connectivity = []

            for conn in raw_connectivity:
                # connectivity MUST hold location IDs (source of truth: loca_schema.json).
                # Handle both string and dict formats; resolve a known location NAME to
                # its ID instead of silently dropping the connection (issue #128).
                if isinstance(conn, str):
                    if conn in location_ids:
                        validated_connectivity.append(conn)
                    elif conn in name_to_id:
                        validated_connectivity.append(name_to_id[conn])
                elif isinstance(conn, dict):
                    if conn.get("locationId") in location_ids:
                        validated_connectivity.append(conn["locationId"])
                    elif conn.get("name") in name_to_id:
                        validated_connectivity.append(name_to_id[conn["name"]])

            location["connectivity"] = validated_connectivity
            
            # CRITICAL FIX: Update context with actual NPC placements
            if context:
                area_id = area_data.get("areaId")
                location_id = location.get("locationId")
                for npc in location.get("npcs", []):
                    npc_name = npc.get("name")
                    # --- CHANGE IS HERE ---
                    npc_description = npc.get("description", "")  # Get the description
                    if npc_name and area_id and location_id:
                        # Update context with full NPC info for better matching
                        context.add_npc(
                            npc_name=npc_name, 
                            area_id=area_id, 
                            location_id=location_id,
                            description=npc_description  # Pass the description
                        )
                        print(f"DEBUG: [Location Generator] Registered/Updated context for: {npc_name} in {area_id}:{location_id}")
            
            # Ensure plot-critical locations have appropriate content
            location_id = location["locationId"]
            
            # Check if this location is referenced in plot
            for plot_point in plot_data.get("plotPoints", []):
                if plot_point.get("location") == location_id:
                    # This is a plot-critical location
                    if not location.get("plotHooks"):
                        location["plotHooks"] = []
                    
                    # Add a plot hook if not already present
                    plot_hint = f"This area seems connected to {plot_point.get('title', 'current events')}"
                    if plot_hint not in location["plotHooks"]:
                        location["plotHooks"].append(plot_hint)
            
            # Set default values for optional fields
            if "encounters" not in location:
                location["encounters"] = []
            if "adventureSummary" not in location:
                location["adventureSummary"] = ""
            if "explorationState" not in location:
                location["explorationState"] = {"status": "unvisited"}
        
        # Post-process: ensure name consistency between map and locations
        if "map" in area_data and "rooms" in area_data["map"]:
            for location in locations:
                # Find the corresponding map room
                for room in area_data["map"]["rooms"]:
                    if room["id"] == location["locationId"]:
                        # If names differ, update map room name to match location
                        if room["name"] != location["name"]:
                            room["name"] = location["name"]
                            print(f"DEBUG: [Location Generator] Updated map room {room['id']} name to match location: {location['name']}")
                        break
        
        return {"locations": locations}
    
    def validate_locations(self, location_data: Dict[str, Any]) -> List[str]:
        """Validate location data against schema and logical consistency"""
        errors = []
        
        # Schema validation for the container
        try:
            # Validate each location individually
            for location in location_data.get("locations", []):
                jsonschema.validate({"locations": [location]}, self.schema)
        except jsonschema.ValidationError as e:
            errors.append(f"Schema validation error: {e.message}")
            return errors
        
        # Content validation
        locations = location_data.get("locations", [])
        location_ids = {loc["locationId"] for loc in locations}
        
        for location in locations:
            loc_id = location["locationId"]
            
            # Check connections are valid
            for conn_id in location.get("connectivity", []):
                if conn_id not in location_ids:
                    errors.append(f"Location {loc_id} connects to non-existent location {conn_id}")
            
            # Check trap DCs are reasonable
            for trap in location.get("traps", []):
                for dc_field in ["detectDC", "disableDC"]:
                    dc_value = trap.get(dc_field, 0)
                    if dc_value < 10 or dc_value > 30:
                        errors.append(f"Location {loc_id} trap '{trap['name']}' has unreasonable {dc_field}: {dc_value}")
            
            # Check danger level consistency
            danger_level = location.get("dangerLevel", "Medium")
            monster_count = sum(m.get("quantity", {}).get("max", 0) for m in location.get("monsters", []))
            trap_count = len(location.get("traps", []))
            
            if danger_level == "Low" and (monster_count > 2 or trap_count > 1):
                errors.append(f"Location {loc_id} marked as Low danger but has many threats")
            elif danger_level == "Very High" and (monster_count == 0 and trap_count == 0):
                errors.append(f"Location {loc_id} marked as Very High danger but has no threats")
        
        return errors
    
    def save_locations(self, location_data: Dict[str, Any], area_id: str, module_name: str = None):
        """Save location data to file using ModulePathManager"""
        path_manager = ModulePathManager(module_name)
        
        # Ensure areas directory exists
        path_manager.ensure_areas_directory()
        
        # Get the proper area file path
        filename = path_manager.get_area_path(area_id)
        
        # Update the area file with full location data if it exists
        if os.path.exists(filename):
            with open(filename, "r") as f:
                area_data = json.load(f)
            
            area_data["locations"] = location_data["locations"]
            
            with open(filename, "w") as f:
                json.dump(area_data, f, indent=2)
            
            print(f"DEBUG: [Location Generator] Updated area file with locations: {filename}")
        else:
            # If area file doesn't exist, just save locations
            with open(filename, "w") as f:
                json.dump(location_data, f, indent=2)
            
            print(f"DEBUG: [Location Generator] Saved locations to: {filename}")

def main():
    """Interactive location generator for testing"""
    generator = LocationGenerator()
    
    print("Location Generator Test")
    print("-" * 50)
    
    # Mock data for testing
    mock_module = {
        "moduleName": "Echoes of the Elemental Forge",
        "moduleDescription": "Ancient dwarven magic threatens the realm",
        "worldSettings": {
            "era": "Age of Reclamation",
            "magicPrevalence": "uncommon"
        }
    }
    
    mock_area = {
        "areaId": "EM001",
        "areaName": "Ember Hollow Mines",
        "areaType": "dungeon",
        "areaDescription": "Abandoned dwarven mines with elemental activity",
        "dangerLevel": "medium",
        "recommendedLevel": 3,
        "locations": [
            {"locationId": "R01", "name": "Mine Entrance", "type": "entrance", "connections": ["R02"]},
            {"locationId": "R02", "name": "Guard Post", "type": "room", "connections": ["R01", "R03"]},
            {"locationId": "R03", "name": "Main Shaft", "type": "corridor", "connections": ["R02", "R04", "R05"]},
            {"locationId": "R04", "name": "Crystal Chamber", "type": "chamber", "connections": ["R03"]},
            {"locationId": "R05", "name": "Forge Room", "type": "hall", "connections": ["R03"]}
        ]
    }
    
    mock_plot = {
        "plotTitle": "Secrets of the Ember Forge",
        "mainObjective": "Stop the Ember cult from awakening the forge",
        "plotPoints": [
            {
                "id": "PP001",
                "title": "The Abandoned Mine",
                "description": "Investigate strange activities in the old mines",
                "location": "R01"
            },
            {
                "id": "PP002", 
                "title": "The Crystal Discovery",
                "description": "Find the source of the elemental crystals",
                "location": "R04"
            }
        ]
    }
    
    # Generate locations
    print("\nGenerating locations...")
    locations = generator.generate_locations(mock_area, mock_plot, mock_module)
    
    # Validate
    errors = generator.validate_locations(locations)
    if errors:
        print("\nValidation errors:")
        for error in errors:
            print(f"  - {error}")
    else:
        print("\nValidation successful!")
        
        # Save
        generator.save_locations(locations, mock_area["areaId"])
        
        # Display summary
        print(f"\nGenerated {len(locations.get('locations', []))} locations")
        for loc in locations.get("locations", []):
            print(f"  - {loc['locationId']}: {loc['name']} ({loc['type']})")
            print(f"    Danger: {loc.get('dangerLevel', 'Unknown')}")
            print(f"    Monsters: {len(loc.get('monsters', []))}")
            print(f"    NPCs: {len(loc.get('npcs', []))}")
            print(f"    Traps: {len(loc.get('traps', []))}")

if __name__ == "__main__":
    main()
